### ISSUE TITLE
Countdown timer embed

### ISSUE THREAD

**Issue by lawsie** [RaspberryPiFoundation/sense-hat-curriculum#1]
In the countdown timer project, Step 2: Creating a dot timer, the embedded project shows up as just the HTML code for an iframe on my browser. 
![iframe](https://cloud.githubusercontent.com/assets/5183697/26159266/0cdb356c-3b16-11e7-84fa-569c7f2dde1c.png)

**Comment by tracygardner** [comment]
Fixed by removing the embed. We decided to remove them based on feedback that children found it really hard to have to scroll up and down within a documents.
