### ISSUE TITLE
Compass project crashes

### ISSUE THREAD

**Issue by lawsie** [RaspberryPiFoundation/sense-hat-curriculum#4]
Trinket crashes when you add the code

```while True:
    print( sense.get_compass() )
```
It works OK if you add a sleep in the loop.

**Comment by rik-cross** [comment]
@tracygardner do you mind taking a look at this one too?

**Comment by rik-cross** [comment]
Marc said: You probably shouldn't use `get_compass` with a sleep, as it needs to do lots of weird maths that gets delayed. `compass_raw` is fine though.

**Comment by tracygardner** [comment]
I can't replicate this (well obviously it worked for me!) so must be just some setups. 

@rik-cross We can't use get_compass_raw() as that doesn't give a heading, just raw magnetometer data. 

The results from get_compass() seem okay with a sleep but I can raise an issue against the sense hat emulator and see what their recommendation is. 

I'll add a sleep for now as that at least stops the freezing.

**Comment by lawsie** [comment]
If it is relevant I'm using Chrome on Windows. I didn't test this one on IE but the rainbow project also crashed for me on IE.

**Comment by tracygardner** [comment]
Thanks Laura, if it crashes on a common Windows setup then we need to fix it. 

How long a sleep did you need to avoid the problem? 

Rik added a 3 second sleep to the Rainbow but that makes it slow to respond which is confusing.

**Comment by lawsie** [comment]
1 second was what I used afaik

**Comment by tracygardner** [comment]
Thanks that's what I'll use then.

**Comment by rik-cross** [comment]
Do we know whether the physical Sense HAT has issues if delays aren't added?

**Comment by lawsie** [comment]
I will have a check today if you like since I spent an hour and a half getting a sense hat working yesterday :D

**Comment by lawsie** [comment]
I can confirm that neither the rainbow nor the compass projects require a sleep using a real sense hat.

**Comment by rik-cross** [comment]
Thanks @lawsie -- in that case I think we instead need to ask Trinket to remove the necessity for a delay in a loop. @tracygardner did you say you had raised an issue with Trinket?

**Comment by tracygardner** [comment]
@lawsie Thanks that's really useful

@rik-cross I said I was going to, but   ... meetings, my Code Club ... But will do it first thing.

**Comment by tracygardner** [comment]
https://github.com/trinketapp/3D-testing/issues/25
